### ISSUE TITLE
xleaflet doesn't build on linux

### ISSUE THREAD

**Issue by marimeireles** [jupyter-xeus/xleaflet#90]
xleafet doesn't build on my ArchLinux, @martinRenou was able to reproduce it on his Fedora.

Steps to reproduce are:

1. Download dependencies with conda
2. Create a build dir
3. CMake
4. make install

And get the following error:

```
Scanning dependencies of target xleaflet
[  3%] Building CXX object CMakeFiles/xleaflet.dir/src/xcircle_marker.cpp.o
[  6%] Building CXX object CMakeFiles/xleaflet.dir/src/xcircle.cpp.o
[  9%] Building CXX object CMakeFiles/xleaflet.dir/src/xcontrol.cpp.o
In file included from /home/mariana/.conda/envs/xleaflet/include/xproperty/xobserved.hpp:20,
                 from /home/mariana/.conda/envs/xleaflet/include/xwidgets/xobject.hpp:18,
                 from /home/mariana/Development/xleaflet/include/xleaflet/xcontrol.hpp:19,
                 from /home/mariana/Development/xleaflet/src/xcontrol.cpp:1:
/home/mariana/Development/xleaflet/include/xleaflet/xcontrol.hpp: In instantiation of ‘xlf::xcontrol<D>::xcontrol() [with D = xw::xmaterialize<xlf::xcontrol>]’:
/home/mariana/.conda/envs/xleaflet/include/xwidgets/xmaterialize.hpp:71:45:   required from ‘xw::xmaterialize<B, P>::xmaterialize(bool, A&& ...) [with A = {}; B = xlf::xcontrol; P = {}]’
/home/mariana/.conda/envs/xleaflet/include/xwidgets/xmaterialize.hpp:63:54:   required from ‘xw::xmaterialize<B, P>::xmaterialize(A&& ...) [with A = {}; B = xlf::xcontrol; P = {}]’
/home/mariana/Development/xleaflet/src/xcontrol.cpp:4:56:   required from here
/home/mariana/Development/xleaflet/include/xleaflet/xcontrol.hpp:43:67: internal compiler error: Segmentation fault
   43 | PROPERTY(std::string, derived_type, position, "topleft", XEITHER("topright", "topleft", "bottomright", "bottomleft"));
      |  
```

I tried to use different versions of `xtensor`, `xeus` and `xwidgets` but didn't make any difference.
Also tried to force the build with a different version of g++ and didn't work either.

**Comment by SylvainCorlay** [comment]
This appears to be a compiler error. Did you consider. I would recommend using the same compiler that is used to build the dependencies. The one drom conda. You can check the xleaflet CI.

**Comment by martinRenou** [comment]
@marimeireles you need to install the compilers from conda-forge: `conda install -c conda-forge compilers` and you should then be able to compile xleaflet.

**Comment by martinRenou** [comment]
You can look at this issue: https://github.com/jupyter-xeus/xleaflet/issues/89

**Comment by marimeireles** [comment]
Oh, that was what I was looking for.
haha I was (almost) sure that you have opened something like that, sorry.
